# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoneyMouse' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MoneyMouse
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Charts'
    pod 'ChameleonFramework'

  target 'MoneyMouseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MoneyMouseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
